apiVersion: network.t-caas.telekom.com/v1alpha1
kind: NodeNetworkConfig
metadata:
  name: vyos-lab-smoke
  namespace: default
spec:
  revision: smoke-0001
  localVRFs:
    smoke-a:
      table: 1000
      staticRoutes:
        - prefix: 198.51.100.0/24
          nextHop:
            address: 192.0.2.1
        - prefix: 2001:db8:100::/64
          nextHop:
            address: 2001:db8::1
